# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UudwpLK6AwKiB8oqQHGsHK7TcUN2Fz7T
"""

from google.colab import drive
drive.mount('/gdrive')

cd ..

!python3 setup.py install

!python3 train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/faster_rcnn_nas_coco.config


cd ../gdrive/My Drive/Major Project /models/research/object_detection

!python3 export_inference_graph.py \
    --input_type image_tensor \
    --pipeline_config_path training/faster_rcnn_nas_coco.config \
    --trained_checkpoint_prefix training/model.ckpt-10727 \
    --output_directory drone_take_five_inference_graph_rcnn

